name: 'Monocle Marketing, LLC'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.78545
title: Monocle Marketing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73187701-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0e12'
    - '#a2c8ed'
    - '#456f99'
    - '#9a9b9d'
    - '#8e3830'
  brandStrength: 0.375
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
